networks:
  backend:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres${POSTGRES_VERSION}
    networks:
      - backend
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}

#  pg_admin:
#    image: dpage/pgadmin4:latest
#    networks:
#      - backend
#    depends_on:
#      - postgres
#    expose:
#      - 5050
#    ports:
#      - 5050:80
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${DBUSER}@test.com
#      - PGADMIN_DEFAULT_PASSWORD=${DBPASS}
#      - PGADMIN_LISTEN_PORT=5050
#      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

  django:
    build:
      context: ../app/
      dockerfile: ../docker/django/web.dockerfile
    networks:
      - backend
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
    entrypoint: >
      bash -c "cd ~; . .profile
      &&  python /app/manage.py migrate
      && hypercorn --bind 0.0.0.0:8000 /app/personal_portfolio.asgi:application"
    depends_on:
      - postgres
    links:
      - postgres:postgres
