version: '3.9'

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  code:


services:
  postgres:
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - backend
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}

  pg_admin:
    image: dpage/pgadmin4:6.9
    networks:
      - backend
    depends_on:
      - postgres
    expose:
      - 5050
    ports:
      - 5050:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

  web:
    build:
      context: ../app/
      dockerfile: ../docker/web/web.dockerfile
    networks:
      - backend
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - DJANGO_SALT=${DJANGO_SALT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    entrypoint: >
      bash -c "cd ~ && . .profile
      && python /app/manage.py migrate
      && python /app/manage.py collectstatic --noinput
      && hypercorn --reload --bind 0.0.0.0:8000 /app/portfolio_django.asgi:application &&
      wait
      "
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ../app
        target: /app
