# persist database volume for local development
volumes:
  data:

services:
  postgres:
    build:
      context: ./database/
      dockerfile: postgres.dockerfile
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASS}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  web:
    build:
      context: ../app/
      dockerfile: ../docker/web/web.dockerfile
    image: web:latest
    tty: true
    ports:
      - 8000:8000
#    command:
#      - bash -c "/opt/venv/bin/python -m hypercorn --reload --bind 0.0.0.0:8000 app.asgi:application"
#      - bash -c "python3 -m hypercorn --bind 127.0.0.1:8000 personal_portfolio.asgi:application"
#    volumes:
#      - type: bind
#        source: ../app/
#        target: /app
#      - data:/var/lib/postgresql
    depends_on:
      - postgres
